AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/*'

# Do not force classes/modules to have documentation
Documentation:
  Enabled: false

# Allow longer lines
LineLength:
  Max: 190

# Tries to force either
#   class Foo
#     class Bar
#     end
#   end
# or
#   class Foo::Bar
#   end
ClassAndModuleChildren:
  Enabled: False
